"""
SIH26074 - Phase 5: Data Access & Analytical Services
----------------------------------------------------
Provides cached access to:
- Static Panchayat terrain & geographic metadata
- Live Phase 3 forecast outputs (data/forecasts/)
- Phase 4 agro-advisory database & dynamic rule evaluation
- District-wide multi-variable risk aggregation
"""

import os
import glob
from typing import Dict, List, Optional, Any, Tuple
import pandas as pd
import numpy as np

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STATIC_PATH = os.path.join(PROJECT_ROOT, "data", "static", "panchayat_terrain_landcover.csv")
FORECAST_DIR = os.path.join(PROJECT_ROOT, "data", "forecasts")
ADVISORY_CSV_PATH = os.path.join(PROJECT_ROOT, "ml", "results", "sample_advisories.csv")

# Caches
_STATIC_DF: Optional[pd.DataFrame] = None
_FORECAST_CACHE: Optional[pd.DataFrame] = None
_FORECAST_MTIME: float = 0.0
_ADVISORY_CACHE: Optional[pd.DataFrame] = None
_ADVISORY_MTIME: float = 0.0


def get_static_panchayats() -> pd.DataFrame:
    """Returns the cached 239 Gram Panchayats dataframe."""
    global _STATIC_DF
    if _STATIC_DF is None:
        if not os.path.exists(STATIC_PATH):
            raise FileNotFoundError(f"Panchayat terrain CSV not found at {STATIC_PATH}")
        _STATIC_DF = pd.read_csv(STATIC_PATH)
    return _STATIC_DF


def get_latest_forecast_file() -> str:
    """Finds the most recent forecast parquet file in data/forecasts/."""
    pattern = os.path.join(FORECAST_DIR, "forecast_*.parquet")
    files = glob.glob(pattern)
    if not files:
        raise FileNotFoundError(f"No forecast parquet files found in {FORECAST_DIR}. Run Phase 3 ingestion first.")
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]


def get_forecast_dataset() -> pd.DataFrame:
    """
    Returns the latest forecast DataFrame from Phase 3, reloading automatically
    if the underlying file on disk has been updated by an ingestion cycle.
    """
    global _FORECAST_CACHE, _FORECAST_MTIME
    latest_file = get_latest_forecast_file()
    current_mtime = os.path.getmtime(latest_file)

    if _FORECAST_CACHE is None or current_mtime > _FORECAST_MTIME:
        df = pd.read_parquet(latest_file)
        _FORECAST_CACHE = df
        _FORECAST_MTIME = current_mtime
    return _FORECAST_CACHE


def get_advisory_dataset() -> pd.DataFrame:
    """
    Returns the advisory database generated by Phase 4.
    """
    global _ADVISORY_CACHE, _ADVISORY_MTIME
    if not os.path.exists(ADVISORY_CSV_PATH):
        raise FileNotFoundError(f"Advisory database not found at {ADVISORY_CSV_PATH}. Run Phase 4 engine first.")
        
    current_mtime = os.path.getmtime(ADVISORY_CSV_PATH)
    if _ADVISORY_CACHE is None or current_mtime > _ADVISORY_MTIME:
        df = pd.read_csv(ADVISORY_CSV_PATH)
        _ADVISORY_CACHE = df
        _ADVISORY_MTIME = current_mtime
    return _ADVISORY_CACHE


def categorize_rainfall(rain_mm: float) -> str:
    """IMD Standard Rainfall Classification Categories."""
    if rain_mm < 0.1:
        return "No Rain"
    elif rain_mm <= 2.4:
        return "Very Light Rain"
    elif rain_mm <= 7.5:
        return "Light Rain"
    elif rain_mm <= 35.5:
        return "Moderate Rain"
    elif rain_mm <= 64.4:
        return "Heavy Rain"
    else:
        return "Very Heavy Rain"


def categorize_heat_stress(temp_c: float, humidity_pct: float) -> str:
    """Heat index / thermal comfort categories."""
    if temp_c <= 7.0 and humidity_pct >= 80.0:
        return "Cold / Frost Alert"
    elif temp_c >= 36.0 and humidity_pct >= 60.0:
        return "Severe Heat Stress"
    elif temp_c >= 35.0 or (temp_c >= 33.0 and humidity_pct >= 65.0):
        return "Moderate Heat Stress"
    elif temp_c >= 38.0 and humidity_pct < 30.0:
        return "Dry Heatwave Stress"
    else:
        return "Normal"


def categorize_spray_window(wind_ms: float, rain_mm: float, temp_c: float) -> str:
    """Chemical spraying window assessment."""
    if wind_ms >= 4.17 or rain_mm >= 2.5:  # 15 km/h or washout rain
        return "Suspended (Drift/Washout Risk)"
    elif wind_ms < 3.0 and rain_mm < 1.0 and temp_c <= 32.0:
        return "Favorable (Morning/Evening Window)"
    else:
        return "Caution (Marginal Conditions)"


def get_panchayat_forecast(gpcode: int, date: Optional[str] = None) -> Dict[str, Any]:
    """
    Retrieves the 5-variable forecast for a specific panchayat, optionally filtered by date.
    """
    static_df = get_static_panchayats()
    p_info = static_df[static_df["GPCODE"] == gpcode]
    if p_info.empty:
        raise ValueError(f"GPCODE {gpcode} not found in Dhanbad Panchayat registry.")
        
    gpname = p_info.iloc[0]["GPNAME"]
    block = p_info.iloc[0]["BLOCK"]

    df = get_forecast_dataset()
    sub = df[df["GPCODE"] == gpcode]
    if sub.empty:
        raise ValueError(f"No forecast predictions available for GPCODE {gpcode}.")
        
    if date:
        sub = sub[sub["DATE"] == date]
        if sub.empty:
            raise ValueError(f"Date '{date}' not found in forecast horizon for GPCODE {gpcode}.")
            
    run_timestamp = sub["RUN_TIMESTAMP"].iloc[0] if "RUN_TIMESTAMP" in sub.columns else None

    # Group by date
    days_data = []
    for d, group in sub.groupby("DATE"):
        var_dict = {}
        for _, r in group.iterrows():
            var_name = r["VARIABLE"]
            var_dict[var_name] = {
                "variable": var_name,
                "predicted_value": round(float(r["PREDICTED_VALUE"]), 2),
                "uncertainty_lower": round(float(r["UNCERTAINTY_LOWER"]), 2),
                "uncertainty_upper": round(float(r["UNCERTAINTY_UPPER"]), 2),
                "confidence_pct": round(float(r["CONFIDENCE_PCT"]), 1)
            }
        days_data.append({
            "date": str(d),
            "predictions": var_dict
        })

    days_data.sort(key=lambda x: x["date"])

    return {
        "gpcode": gpcode,
        "panchayat": gpname,
        "block": block,
        "run_timestamp": run_timestamp,
        "forecast_days_count": len(days_data),
        "forecasts": days_data
    }


def get_panchayat_advisories(
    gpcode: int,
    date: Optional[str] = None,
    crop: Optional[str] = None
) -> Dict[str, Any]:
    """
    Retrieves agro-advisories for a given panchayat, with optional date and crop filtering.
    """
    static_df = get_static_panchayats()
    p_info = static_df[static_df["GPCODE"] == gpcode]
    if p_info.empty:
        raise ValueError(f"GPCODE {gpcode} not found in Dhanbad Panchayat registry.")
        
    gpname = p_info.iloc[0]["GPNAME"]
    block = p_info.iloc[0]["BLOCK"]

    adv_df = get_advisory_dataset()
    sub = adv_df[adv_df["GPCODE"] == gpcode]
    if sub.empty:
        raise ValueError(f"No advisories available for GPCODE {gpcode}.")
        
    if date:
        sub = sub[sub["DATE"] == date]
        if sub.empty:
            raise ValueError(f"No advisories found for GPCODE {gpcode} on date '{date}'.")
            
    if crop:
        sub = sub[sub["CROP"].str.contains(crop, case=False, na=False)]
        if sub.empty:
            raise ValueError(f"No advisories found for crop matching '{crop}'.")

    items = []
    for _, r in sub.iterrows():
        items.append({
            "gpcode": int(r["GPCODE"]),
            "panchayat": str(r["PANCHAYAT"]),
            "block": str(r["BLOCK"]),
            "date": str(r["DATE"]),
            "crop": str(r["CROP"]),
            "advisory_text": str(r["ADVISORY_TEXT"]),
            "triggering_variables": str(r["TRIGGERING_VARIABLES"]),
            "confidence_pct": round(float(r["CONFIDENCE_PCT"]), 1)
        })

    return {
        "gpcode": gpcode,
        "panchayat": gpname,
        "block": block,
        "date_filtered": date,
        "crop_filtered": crop,
        "total_advisories": len(items),
        "advisories": items
    }


def get_district_risk_summary(date: Optional[str] = None) -> Dict[str, Any]:
    """
    Generates an aggregated risk summary across all 239 Panchayats for a specified date
    (or the earliest available date if unspecified).
    """
    df = get_forecast_dataset()
    available_dates = sorted(df["DATE"].unique().tolist())
    
    if not available_dates:
        raise ValueError("Forecast store contains no available dates.")
        
    target_date = date or available_dates[0]
    if target_date not in available_dates:
        raise ValueError(f"Requested date '{target_date}' not found in forecast horizon ({available_dates[0]} to {available_dates[-1]}).")
        
    sub_df = df[df["DATE"] == target_date]
    run_timestamp = sub_df["RUN_TIMESTAMP"].iloc[0] if "RUN_TIMESTAMP" in sub_df.columns else None

    # Pivot 5 variables per GPCODE
    piv = sub_df.pivot(index="GPCODE", columns="VARIABLE", values="PREDICTED_VALUE").reset_index()
    conf = sub_df.groupby("GPCODE")["CONFIDENCE_PCT"].mean().reset_index()
    piv = piv.merge(conf, on="GPCODE")

    # Merge static geography
    static_df = get_static_panchayats()
    merged = static_df.merge(piv, on="GPCODE", how="inner")

    risk_items = []
    risk_counts = {
        "No Rain": 0,
        "Very Light Rain": 0,
        "Light Rain": 0,
        "Moderate Rain": 0,
        "Heavy Rain": 0,
        "Very Heavy Rain": 0
    }

    for _, r in merged.iterrows():
        gpcode = int(r["GPCODE"])
        gpname = str(r["GPNAME"])
        block = str(r["BLOCK"])
        lat = float(r["LATITUDE"])
        lon = float(r["LONGITUDE"])
        
        rain = float(r["RAINFALL"])
        temp = float(r["TEMPERATURE"])
        hum = float(r["HUMIDITY"])
        wind = float(r["WIND_SPEED"])
        et = float(r["EVAPOTRANSPIRATION"])
        conf_val = float(r["CONFIDENCE_PCT"])

        rain_cat = categorize_rainfall(rain)
        risk_counts[rain_cat] = risk_counts.get(rain_cat, 0) + 1

        heat_cat = categorize_heat_stress(temp, hum)
        spray_cat = categorize_spray_window(wind, rain, temp)

        risk_items.append({
            "gpcode": gpcode,
            "panchayat": gpname,
            "block": block,
            "latitude": round(lat, 4),
            "longitude": round(lon, 4),
            "rainfall_mm": round(rain, 2),
            "rainfall_risk_level": rain_cat,
            "temperature_c": round(temp, 2),
            "heat_stress_level": heat_cat,
            "humidity_pct": round(hum, 1),
            "wind_speed_ms": round(wind, 2),
            "spray_window_status": spray_cat,
            "evapotranspiration_mm": round(et, 2),
            "confidence_pct": round(conf_val, 1)
        })

    rain_values = [item["rainfall_mm"] for item in risk_items]
    rainfall_summary = {
        "min_mm": round(float(np.min(rain_values)), 2),
        "mean_mm": round(float(np.mean(rain_values)), 2),
        "max_mm": round(float(np.max(rain_values)), 2),
        "panchayats_with_rain": int(np.sum(np.array(rain_values) >= 0.1)),
        "panchayats_heavy_rain": int(np.sum(np.array(rain_values) >= 35.6))
    }

    return {
        "date": target_date,
        "run_timestamp": run_timestamp,
        "total_panchayats": len(risk_items),
        "rainfall_summary": rainfall_summary,
        "risk_distribution": risk_counts,
        "panchayat_risk_assessments": risk_items
    }
